name: Deploy Application

on:
  push:
    branches:
      - develop
      - 'feature/aws-deployment-with-CI/CD'
  workflow_dispatch:

# Permission for GitHub Container Registry
permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.test
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/reposage-backend:latest

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.test
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/reposage-frontend:latest

      - name: Deploy to EC2 instance via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            export GITHUB_USERNAME=${{ github.repository_owner }}
            export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            bash ~/pull.sh 